# Generated by Django 4.2.9 on 2024-07-22 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id_cam', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('immatriculation', models.CharField(max_length=20)),
                ('transporteur', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chaffeur',
            fields=[
                ('id_chauffeur', models.AutoField(db_column='id_chauffeur', primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('permis', models.CharField(max_length=255, null=True)),
                ('telephone', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id_commentaire', models.AutoField(db_column='id_commentaire', primary_key=True, serialize=False)),
                ('texte', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement0',
            fields=[
                ('id_mvt', models.AutoField(primary_key=True, serialize=False)),
                ('statut_entree', models.IntegerField()),
                ('statut_sortie', models.IntegerField(blank=True, null=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('date_entree', models.DateTimeField(blank=True, null=True)),
                ('remorque', models.CharField(max_length=255, null=True)),
                ('destination', models.CharField(max_length=255, null=True)),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements0', to='home.camion')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements0', to='home.chaffeur')),
                ('commentaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements0', to='home.commentaire')),
            ],
        ),
        migrations.CreateModel(
            name='ParametrageDelais',
            fields=[
                ('id_para', models.AutoField(db_column='id_para', primary_key=True, serialize=False)),
                ('entite', models.CharField(max_length=255)),
                ('nbr_max', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=20)),
                ('delais_maximal', models.CharField(max_length=20)),
                ('delais_urgent', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transitaire',
            fields=[
                ('id_transit', models.AutoField(db_column='id_transit', primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id_user', models.AutoField(db_column='id_user', primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('matricule', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('poste', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement3',
            fields=[
                ('id_mvt', models.AutoField(primary_key=True, serialize=False)),
                ('statut_entree', models.IntegerField()),
                ('statut_sortie', models.IntegerField(blank=True, null=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('date_entree', models.DateTimeField(blank=True, null=True)),
                ('remorque', models.CharField(max_length=255, null=True)),
                ('mission', models.CharField(max_length=255, null=True)),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements3', to='home.camion')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements3', to='home.chaffeur')),
                ('id_mvt_0', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements3', to='home.mouvement0')),
                ('pointeur_entree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_entree3', to='home.utilisateurs')),
                ('pointeur_sortie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_sortie3', to='home.utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement2',
            fields=[
                ('id_mvt', models.AutoField(primary_key=True, serialize=False)),
                ('statut_entree', models.IntegerField()),
                ('statut_sortie', models.IntegerField(blank=True, null=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('date_entree', models.DateTimeField(blank=True, null=True)),
                ('remorque', models.CharField(max_length=255, null=True)),
                ('mission', models.CharField(max_length=255, null=True)),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements2', to='home.camion')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements2', to='home.chaffeur')),
                ('id_mvt_0', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements2', to='home.mouvement0')),
                ('pointeur_entree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_entree2', to='home.utilisateurs')),
                ('pointeur_sortie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_sortie2', to='home.utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement1',
            fields=[
                ('id_mvt', models.AutoField(primary_key=True, serialize=False)),
                ('statut_entree', models.IntegerField()),
                ('statut_sortie', models.IntegerField(blank=True, null=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('date_entree', models.DateTimeField(blank=True, null=True)),
                ('remorque', models.CharField(max_length=255, null=True)),
                ('mission', models.CharField(max_length=255, null=True)),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='home.camion')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='home.chaffeur')),
                ('id_mvt_0', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='home.mouvement0')),
                ('pointeur_entree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_entree', to='home.utilisateurs')),
                ('pointeur_sortie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_sortie', to='home.utilisateurs')),
            ],
        ),
        migrations.AddField(
            model_name='mouvement0',
            name='pointeur_entree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_entree0', to='home.utilisateurs'),
        ),
        migrations.AddField(
            model_name='mouvement0',
            name='pointeur_sortie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_sortie0', to='home.utilisateurs'),
        ),
        migrations.AddField(
            model_name='mouvement0',
            name='transitaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements0', to='home.transitaire'),
        ),
    ]
