# Generated by Django 4.2.9 on 2024-09-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement3',
            name='representant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RepresentantMouvement', to='home.transitaire'),
        ),
        migrations.AddField(
            model_name='mouvement3',
            name='transitaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TransitaireMouvement', to='home.transitaire'),
        ),
    ]
