# Generated by Django 4.2.9 on 2024-07-10 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id_cam', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('immatriculation', models.CharField(max_length=20)),
                ('transporteur', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chaffeur',
            fields=[
                ('id_chauffeur', models.AutoField(db_column='id_chauffeur', primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('permis', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mouvement',
            fields=[
                ('id_mvt', models.AutoField(primary_key=True, serialize=False)),
                ('statut_entree', models.IntegerField()),
                ('statut_sortie', models.IntegerField(blank=True, null=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('date_entree', models.DateTimeField(blank=True, null=True)),
                ('remorque', models.CharField(max_length=255, null=True)),
                ('mission', models.CharField(max_length=255, null=True)),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='home.camion')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='home.chaffeur')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id_user', models.AutoField(db_column='id_user', primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('matricule', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('poste', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='mouvement',
            name='pointeur_entree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_entree', to='home.utilisateurs'),
        ),
        migrations.AddField(
            model_name='mouvement',
            name='pointeur_sortie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_sortie', to='home.utilisateurs'),
        ),
    ]
