# Generated by Django 4.2.9 on 2024-09-13 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mouvement3_representant_mouvement3_transitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement0',
            name='representant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RepresentantMouvement0', to='home.transitaire'),
        ),
    ]
