# Generated by Django 4.2.9 on 2024-07-10 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_camion_chaffeur_mouvement_utilisateurs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouvement0',
            fields=[
                ('id_mvt', models.AutoField(primary_key=True, serialize=False)),
                ('statut_entree', models.IntegerField()),
                ('statut_sortie', models.IntegerField(blank=True, null=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('date_entree', models.DateTimeField(blank=True, null=True)),
                ('remorque', models.CharField(max_length=255, null=True)),
                ('destination', models.CharField(max_length=255, null=True)),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements0', to='home.camion')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements0', to='home.chaffeur')),
                ('pointeur_entree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_entree0', to='home.utilisateurs')),
                ('pointeur_sortie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_sortie0', to='home.utilisateurs')),
            ],
        ),
        migrations.AddField(
            model_name='mouvement',
            name='id_mvt_0',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='home.mouvement0'),
        ),
    ]
