# Generated by Django 4.2.9 on 2024-07-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mouvement0_mouvement_id_mvt_0'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mouvement',
            new_name='Mouvement1',
        ),
    ]
