# Generated by Django 4.2.9 on 2024-09-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mouvement0_representant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvement0',
            name='zone_entree',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='mouvement0',
            name='zone_sortie',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='mouvement1',
            name='zone_entree',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='mouvement1',
            name='zone_sortie',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='mouvement2',
            name='zone_entree',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='mouvement2',
            name='zone_sortie',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='mouvement3',
            name='zone_entree',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='mouvement3',
            name='zone_sortie',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='mouvement4',
            name='zone_entree',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='mouvement4',
            name='zone_sortie',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='mouvement5',
            name='zone_entree',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='mouvement5',
            name='zone_sortie',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='mouvement6',
            name='zone_entree',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='mouvement6',
            name='zone_sortie',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='mouvement7',
            name='zone_entree',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='mouvement7',
            name='zone_sortie',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='mouvement8',
            name='zone_entree',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='mouvement8',
            name='zone_sortie',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
