# Generated by Django 4.2.9 on 2024-07-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_mouvement_mouvement1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mouvement2',
            fields=[
                ('id_mvt', models.AutoField(primary_key=True, serialize=False)),
                ('statut_entree', models.IntegerField()),
                ('statut_sortie', models.IntegerField(blank=True, null=True)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('date_entree', models.DateTimeField(blank=True, null=True)),
                ('remorque', models.CharField(max_length=255, null=True)),
                ('mission', models.CharField(max_length=255, null=True)),
                ('camion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements2', to='home.camion')),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements2', to='home.chaffeur')),
                ('id_mvt_0', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements2', to='home.mouvement0')),
                ('pointeur_entree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_entree2', to='home.utilisateurs')),
                ('pointeur_sortie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_sortie2', to='home.utilisateurs')),
            ],
        ),
    ]
