# Generated by Django 4.2.9 on 2024-09-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_mouvement0_zone_entree_mouvement0_zone_sortie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='commentaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
