# Generated by Django 4.2.9 on 2024-09-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_observation_commentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liaison',
            fields=[
                ('id_link', models.AutoField(primary_key=True, serialize=False)),
                ('conteneur1', models.CharField(max_length=255)),
                ('conteneur2', models.CharField(blank=True, max_length=255, null=True)),
                ('conteneur3', models.CharField(blank=True, max_length=255, null=True)),
                ('type1', models.CharField(max_length=255)),
                ('type2', models.CharField(blank=True, max_length=255, null=True)),
                ('type3', models.CharField(blank=True, max_length=255, null=True)),
                ('id_mvt_sm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkmouvements_sm', to='home.mouvement0')),
                ('id_mvt_vrac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkmouvements_vrac', to='home.mouvement0')),
            ],
        ),
    ]
