# Generated by Django 4.2.9 on 2024-07-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_parametragedelais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametragedelais',
            name='id_para',
            field=models.AutoField(db_column='id_para', primary_key=True, serialize=False),
        ),
    ]
