# Generated by Django 4.2.9 on 2024-09-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_liaison'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mouvement3',
            old_name='gatepass',
            new_name='numconteneur4',
        ),
        migrations.RenameField(
            model_name='mouvement3',
            old_name='pregate',
            new_name='numconteneur5',
        ),
        migrations.AddField(
            model_name='mouvement0',
            name='numconteneur4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mouvement0',
            name='numconteneur5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mouvement0',
            name='typeconteneur4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mouvement0',
            name='typeconteneur5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mouvement3',
            name='typeconteneur4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mouvement3',
            name='typeconteneur5',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
